# Load the Dataset

In [1]:
import pandas as pd
import numpy as np
import random
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris = pd.read_csv(url, 
            header=None,
            names = ['sepal_length', 
                     'sepal_width', 
                     'petal_length', 
                     'petal_width', 
                     'species'])

In [65]:
## Definitions of classifying classes
classes = list(pd.unique(iris.species))
numClasses = len(classes)

## Extracting the Feature Matrix

In [66]:
X = np.matrix(iris.iloc[:, 0:4])
X = X.astype(np.float)
m, n = X.shape

## Extracting the response

In [67]:
y = np.asarray(iris.species)

## Extracting features for different classes

In [68]:
CLS = []
for each in classes:
    CLS.append(np.matrix(iris[iris.species == each].iloc[:, 0:4]))

In [69]:
len(CLS)

3

## The real meat

#### Calculating the mean and variance of each features for each class

In [70]:
pArray = []
def calculate_mean_and_variance(CLS, n, numClasses):
    for i in range(numClasses):
        pArray.append([])
        for x in range(n):
            mean = np.mean(CLS[i][:, x])
            var = np.var(CLS[i][:, x])
            pArray[i].append([mean, var])

In [71]:
calculate_mean_and_variance(CLS, n, numClasses)
for each in pArray:
    print(each, end='\n\n')

[[5.0060000000000002, 0.12176400000000002], [3.4180000000000001, 0.14227600000000001], [1.464, 0.029504000000000002], [0.24399999999999999, 0.011264000000000003]]

[[5.9359999999999999, 0.261104], [2.7700000000000005, 0.096500000000000016], [4.2599999999999998, 0.21640000000000004], [1.3259999999999998, 0.038323999999999997]]

[[6.5879999999999983, 0.39625600000000011], [2.9740000000000002, 0.10192399999999999], [5.5520000000000005, 0.29849600000000004], [2.0260000000000002, 0.07392399999999999]]



#### Choosing training dataset (Random Choosing)

In [72]:
# Choosing 70% of the dataset for training Randomly
random_index = random.sample(range(m), int(m * 0.7))

In [ ]:
def probability(mean, stdev, x):
    

#### Creating the actual Baysean Classifier

In [61]:
def classify_baysean():
    correct_predictions = 0
    for index in random_index:
        result = []
        x = X[index, :]
        for eachClass in range(numClasses):
            result.append([])
            prior = 1 / numClasses
            
            # For sepal_length
            prosterior_feature_1 = probability(pArray[index][0][0], 
                                               pArray[index][0][1], 
                                               x[0])
            # For sepal_width
            prosterior_feature_2 = probability(pArray[index][1][0],
                                              pArray[index][1][1],
                                              x[1])
            # For petal_length
            prosterior_feature_3 = probability(pArray[index][2][0],
                                              pArray[index][2][1],
                                              x[2])
            # For petal_width
            prosterior_feature_4 = probability(pArray[index][3][0],
                                              pArray[index][3][1],
                                              x[3])
            joint = prosterior_feature_1 * prosterior_feature_2 * \
            prosterior_feature_3 * prosterior_feature_4 * prior
            result[index].append(joint)
        print(result[index])

In [62]:
classify_baysean()

NameError: name 'probability' is not defined

In [98]:
x = X[49,:][:, 0]

In [99]:
x

matrix([[ 5.]])

In [100]:
import math

In [102]:
mean = pArray[0][0][0]
stdev = pArray[0][0][1]
exponent = math.exp(-(math.pow(x-mean,2)/(2*stdev)))

In [103]:
exponent

0.99985218398194

In [3]:
a = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [5]:
for attribute in zip(*a):
    print(attribute)

(1, 5)
(2, 6)
(3, 7)
(4, 8)


In [6]:
df = pd.DataFrame(np.random.randn(100, 2))

In [7]:
df

0         1
0   0.891914 -0.957444
1   0.500691 -2.259443
2  -2.719203  0.123332
3  -0.910284  2.364859
4   1.375659 -0.455953
5  -0.661848 -0.877416
6   0.368729 -0.536522
7   0.866648  2.182499
8  -0.522822 -0.570511
9  -0.206031  0.648060
10  1.213100 -0.710189
11 -0.761086 -0.422410
12  0.164639 -1.004728
13  1.169840  1.035104
14  0.074590 -1.401222
15  0.552037 -0.047192
16  0.783914 -1.125556
17 -0.184240  0.193157
18  0.970510 -0.051371
19 -0.367723 -0.021025
20 -0.883345  0.116409
21  0.992421 -0.792637
22  1.426434 -0.679730
23 -0.790068 -0.157665
24 -1.543924 -0.793718
25  0.835844  1.307662
26  0.487385  0.544462
27  0.404973  1.030814
28 -0.224405  0.357701
29 -0.447075  1.836367
..       ...       ...
70  1.338269  1.484710
71 -0.883285 -0.141153
72 -0.447681 -1.758202
73 -1.228454 -0.646145
74  0.178335  1.158356
75  1.665174 -1.576035
76  0.460147 -2.488727
77 -0.123505 -0.366446
78 -3.887232 -0.489308
79 -0.360444  0.832431
80 -0.864867 -0.857648
81  1.424193  0.708941
82 -0.346798 -1.091791
83  0.926461 -0.442008
84  0.333903 -0.042515
85  0.125269 -1.311858
86  1.099426 -0.602258
87 -1.046655 -2.135608
88 -0.807969 -0.389795
89 -1.418035  1.539792
90 -0.288480  0.749006
91  2.043575 -0.269924
92 -1.179398 -0.496812
93  0.471483 -0.220843
94 -0.615731 -0.656167
95 -0.641456  0.852312
96  0.155349  0.041979
97 -0.780068  1.888171
98  0.673478 -0.573956
99 -0.887921  0.640687

[100 rows x 2 columns]

In [10]:
msk = np.random.rand(len(df)) < 0.8

array([ 0.33154805,  0.61087702,  0.37280772,  0.16430062,  0.32055341,
        0.78054295,  0.59793812,  0.71819783,  0.60655645,  0.07863817,
        0.24856861,  0.72289622,  0.83113749,  0.83097412,  0.00238536,
        0.24239049,  0.10110951,  0.90110105,  0.11722661,  0.7905132 ,
        0.23419997,  0.1418044 ,  0.64367201,  0.04223493,  0.4717505 ,
        0.96530716,  0.93529566,  0.63355559,  0.79085357,  0.00876183,
        0.84564062,  0.31206604,  0.14575479,  0.45583297,  0.61052447,
        0.65446117,  0.18073058,  0.934495  ,  0.92384596,  0.89867522,
        0.75511463,  0.88812033,  0.41271355,  0.90124828,  0.81312626,
        0.15097639,  0.56955865,  0.16152587,  0.79198413,  0.22668628,
        0.80533283,  0.24454383,  0.91311159,  0.67802587,  0.08664223,
        0.96222874,  0.83982512,  0.80954589,  0.54148041,  0.07299198,
        0.87857954,  0.13720646,  0.39491333,  0.49274505,  0.59749372,
        0.93311245,  0.60194483,  0.52511294,  0.27740221,  0.37

In [9]:
msk

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False, False,  True,  True, False, False,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True, False,  True,  True, False, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,  True], dtype=bool)